#+TITLE: An ABAQUS-MATLAB tutorial for Jointed Systems
#+AUTHOR: Nidish Narayanaa Balaji
#+EXPORT_FILE_NAME: index.html
#+OPTIONS: startup:indent
#+HTML_HEAD: <base target="_blank">
#+latex_header: \usepackage[margin=0.8in]{geometry} \usepackage{cleveref}
# #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup
#+HTML: <style> summary:hover {background:pink;} </style>
#+HTML: <script>var HS_STARTUP_FOLDED = true;</script>
# #+HTML_HEAD: <style> #content{max-width:2000px;} *{font-size: large;}</style>
# #+HTML_HEAD: <link rel="stylesheet" href="./themes/codize.css">

#+LATEX: \pagebreak

* Introduction
This tutorial has been prepared to help researchers get started with modeling jointed systems for use in nonlinear vibration contexts.
A three-bolted lap joint system known as the Brake-Reu{\ss} Beam (read more about the benchmark [[https://jointmechanics.org/index.php/Benchmarks#The_Brake-Reu%C3%9F_Beams][here]]) is used for the demonstrations.
We will start with making the model using CAD and go all the way to doing a simple nonlinear prestress calculation.

It is understood that not everyone will be interested in each step of the tutorial, so intermediate files are saved and are available in the repository.
This should help the reader start at any desired intermediate step.

Here is an overview of the sections and their contents:
1. *Preprocessing* ([[Cref:sec:prepro]]): discusses the CAD modeling ([[cref:sec:modeling]]) of the parts along with necessary set creation ([[cref:sec:setcreat]]). Of particular note here is the *realization of bolt prestress* (see more in [[cref:sec:boltprel]]), which is done in a manner that is most convenient for linear and nonlinear vibration simulations including prestress effects.
   
   _The model at the end of this step can be found in [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step0.cae][model\under{}step0.cae]]._
2. *Constraints* ([[Cref:sec:constr]]): discusses the relevant constraints for the tied interfaces (washers are fully tied, for instance), and the bolt preload realization ([[cref:sec:boltprel]]).

   _The model at the end of this step can be found in [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1.cae][model\under{}step1.cae]]._
3. *Meshing* ([[Cref:sec:meshing]]): discusses the seeded meshing procedure. This section also includes instructions for an optional abaqus static prestress simulation ([[cref:sec:abqprs]]) that can be used to verify the correctness of the model so far.

   _The model at the end of this step can be found in [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1a.cae][model\under{}step1a.cae]]. Additionally, [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step2.cae][model\under{}step2.cae]] is also available, which includes the above prestress test._
4. *Mesh Process* ([[Cref:sec:meshproc]]): discusses processing the mesh and includes selection of an output node, reorganization of node sets (so that the bottom interface nodes are right below the top), and provides instructions on setting up the Hurty/Craig-Bampton (HCB) procedure. It ends with instructions to run the job required for generating substructured matrices.
5. *Matrix Extraction* ([[Cref:sec:mex]]): discusses the format of the outputted matrix and provides a bash-python script to postprocess it ([[cref:sec:bscr]]). Additionally a MATLAB/Octave tutorial is provide ([[cref:sec:nlan]]) which conducts *nonlinear prestress analysis with sub-100 lines of code*.
   _The model at the end of everything can be found in [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step3.cae][model\under{}step3.cae]]._
6. *Relative Coordinates Pipeline* ([[Cref:sec:relcsp]]): discusses the pipeline that needs to be followe in ABAQUS for using relative coordinate DOFS. *This provides an ~2x reduction in model size without any approximations*, and is therefore recommended always.
   This is presented as a separate section since it requires some experience with ABAQUS before following all the steps that are involved here.

   When the relative coordinate DOFs format is desired, [[cref:sec:meshproc]] and [[cref:sec:mex]] don't need to be followed. This can be substituted completely with [[cref:sec:relcsp]].
7. *Outro/Contact* ([[Cref:sec:outro]]): Concludes the tutorial, giving contact information of the authors, etc.
#+latex: \pagebreak
* Preprocess
:PROPERTIES:
:CUSTOM_ID: sec:prepro
:END:

The Brake-ReuÃŸ Beam (BRB) is a 3-bolted lap-joint beam which will serve as our tutorial joint structure (read more about the benchmark [[https://jointmechanics.org/index.php/Benchmarks#The_Brake-Reu%C3%9F_Beams][here]]).
To make the tutorial self-contained, the tutorial will begin with CAD-modeling of the BRB in ABAQUS and take you all the way to matrix extraction and nonlinear dynamics analysis on MATLAB/OCTAVE.
Buckle up! :)

#+CAPTION: Geometry of the BRB Benchmark
#+NAME: fig:brbgeom
#+ATTR_HTML: :width 300px :class zoomable-image :align center
#+ATTR_LATEX: :width 0.5\textwidth
[[./figs/300px-BRB.png]]

A picture of the parts of the BRB is shown in Fig. [[fig:brbgeom]] and this will be used to guide the modeling here.
Standard 5/16 bolt-nut-washers will be used for the assembly. Since Bolt thread interactions won't be modeled here, the bolt shank is modeled as a smooth cylinder (see [[cref:sec:boltprel]] for more details on bolt prestress modeling).

*Note*: If you already have a model of your structure and want to just apply the node-selection/matrix extraction, you can safely ignore the sections particular to the modeling of the BRB and just go through the remaining, whose instructions are quite general.
The general principles in the modeling section are, however, recommended for all jointed structure modeling.

** A Note on Python Scripting                                       :Script:
ABAQUS Python scripting is quite powerful and will be used quite liberally throughout this tutorial. The following are some tips/tricks to get started for beginners:
+ For beginners, the easiest way to start scripting is to open up CAE (the GUI) and do the necessary tasks. ABAQUS would have saved the actions in a Python file called =abaqus.rpy=. This is just python code that can be imported into ABAQUS to repeat the same tasks.
  All standard python commands work so this makes it very helpful.
+ On Windows the *work directory* may be an unfamiliar concept (on Linux it is just the directory from which ABAQUS is launched). This directory can be manually set by ~File->Set Work Directory~, following which all the files (including the =ABAQUS.rpy= file) will be put in the specified folder.
+ Fig [[fig:ovw]] shows a pictorial overview of the different options available in ABAQUS for scripting support. The ABAQUS PDE can be used for ABAQUS python script development.
#+CAPTION: Options in ABAQUS for Scripting
#+ATTR_HTML: :width 600px :class zoomable-image :align center
#+ATTR_LATEX: :width \textwidth
#+NAME: fig:ovw
[[./figs/ovw.png]]

** Modeling Parts                                               :Script:GUI:
:PROPERTIES:
:CUSTOM_ID: sec:modeling
:END:
We will first model the two "halves" of the BRB. The following steps enumerate the process (can be skipped if you already have a model).

We will do the construction through ABAQUS Python code that can be imported through =File->Run Script= or just typed into the command line.

1. First import the following code to import all the necessary objects and then the material properties (steel, here).
   #+begin_src python -n :tangle yes
     # -*- coding: utf-8 -*-
     import sys

     from part import *
     from material import *
     from section import *
     from assembly import *
     from step import *
     from interaction import *
     from load import *
     from mesh import *
     from optimization import *
     from job import *
     from sketch import *
     from visualization import *
     from connectorBehavior import *

     mdl = mdb.models['Model-1']
     ##############################
     # MATERIAL PROPERTIES: STEEL #
     ##############################
     mdl.Material(name='STEEL')

     steel = mdl.materials['STEEL']
     steel.Density(table=((7800.0, ), ))
     steel.Elastic(table=((2e11, 0.29),))
     mdl.HomogeneousSolidSection(material='STEEL', name=
                                 'Section-1', thickness=None)
   #+end_src
   The above code creates a new material called "STEEL", with Young's Modulus 200GPa, Poisson's ratio 0.29, and density 7800 kg/m^3.
2. Now use the following to model the half beam (this can be done on CAE with the GUI quite easily).
   #+begin_src python +n :tangle yes
     mdl = mdb.models['Model-1']

     ###################
     # PART : HALFBEAM #
     ###################
     # 1. Sketch and Extrude
     mdl.ConstrainedSketch(name='__profile__', sheetSize=2.0)
     sktch = mdl.sketches['__profile__']
     sktch.Line(point1=(-36e-2, 1.27e-2), point2=(-6e-2, 1.27e-2))
     sktch.Line(point1=(-6e-2, 1.27e-2), point2=(-6e-2, 0))
     sktch.Line(point1=(-6e-2, 0), point2=(6e-2,0))
     sktch.Line(point1=(6e-2,0), point2=(6e-2,-1.27e-2))
     sktch.Line(point1=(6e-2,-1.27e-2), point2=(-36e-2,-1.27e-2))
     sktch.Line(point1=(-36e-2,-1.27e-2), point2=(-36e-2,1.27e-2))

     mdl.Part(dimensionality=THREE_D, name='HALFBEAM', type=DEFORMABLE_BODY)
     hfbm = mdl.parts['HALFBEAM']
     hfbm.BaseSolidExtrude(depth=25.4e-3, sketch=sktch)
     del sktch

     # 2. Cut out Holes
     mdl.ConstrainedSketch(name='__profile__', sheetSize=2.0,
                           transform=
                           hfbm.MakeSketchTransform(
                               sketchPlane=hfbm.faces[2],
                               sketchPlaneSide=SIDE1,
                               sketchUpEdge=hfbm.edges[8],
                               sketchOrientation=RIGHT,
                               origin=(0.0, 0.0, 1.27e-2)))
     sktch = mdl.sketches['__profile__']
     cs = [-3e-2, 0.0, 3e-2];
     gs = []
     for i in range(3):
         gs.append(sktch.CircleByCenterPerimeter(center=(cs[i], 0),
                                                 point1=(cs[i]+0.85e-2/2, 0)))

     hfbm.CutExtrude(sketchPlane=hfbm.faces[2], sketchPlaneSide=SIDE1,
                     sketchUpEdge=hfbm.edges[8],
                     sketchOrientation=RIGHT, sketch=sktch)


     # 3. Partition object
     hfbm.PartitionCellByExtendFace(cells=hfbm.cells,
                                    extendFace=hfbm.faces[6])
     hfbm.PartitionCellByExtendFace(cells=hfbm.cells,
                                    extendFace=hfbm.faces[7])

     mdl.ConstrainedSketch(name='__profile__', sheetSize=2.0,
                           gridSpacing=30e-3, transform=
                           hfbm.MakeSketchTransform(
                               sketchPlane=hfbm.faces[11],
                               sketchPlaneSide=SIDE1,
                               sketchUpEdge=hfbm.edges[27],
                               sketchOrientation=RIGHT,
                               origin=(0.0, 0.0, 1.27e-2)))
     sktch = mdl.sketches['__profile__']
     cs = [-3e-2, 0.0, 3e-2];
     wor = i2m*0.34375
     for i in range(3):
         sktch.CircleByCenterPerimeter(center=(cs[i], 0),
                                       point1=(cs[i]+wor, 0))
     hfbm.PartitionCellBySketch(cells=hfbm.cells, sketch=sktch,
                                sketchUpEdge=hfbm.edges[27],
                                sketchPlane=hfbm.faces[11])
     hfbm.PartitionCellByExtrudeEdge(cells=hfbm.cells, edges=hfbm.edges[0],
                                     line=hfbm.edges[-1], sense=FORWARD)
     hfbm.PartitionCellByExtrudeEdge(cells=hfbm.cells, edges=hfbm.edges[3],
                                     line=hfbm.edges[-1], sense=FORWARD)
     hfbm.PartitionCellByExtrudeEdge(cells=hfbm.cells, edges=hfbm.edges[6],
                                     line=hfbm.edges[-1], sense=FORWARD)

     pt = hfbm.InterestingPoint(edge=hfbm.edges[-2], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[-2])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[75], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[75])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[39], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[39])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[85], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[85])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[39], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[39])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[41], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[41])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[111], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[111])

     pt = hfbm.InterestingPoint(edge=hfbm.edges[135], rule=MIDDLE)
     hfbm.PartitionCellByPlanePointNormal(cells=hfbm.cells, point=pt,
                                          normal=hfbm.edges[135])

     # 4. Assign Material
     regn = hfbm.Set(cells=hfbm.cells, name='Set-1')
     hfbm.SectionAssignment(region=regn, sectionName='Section-1')
   #+end_src
#+begin_details Scripting note :background-color "#cccccc" :title-color "black"
You can see that certain faces and edges were used in the above.
A quick way to check which face is what will be to use the =highlight= command on the ABAQUS python console.
Here is an example:
#+ATTR_HTML: :width 600px
[[./figs/highl.png]]
#+end_details
   At the end of this step, you should have a partitioned part that looks like this.
   The partitioning is done in this way to help with the seeded meshing, constraint enforcement, etc.
   #+ATTR_HTML: :width 600px
   [[./figs/parthb.png]]
   #+begin_Details IMPORTANT! Geometry Correction Note :background-color "#cccccc" :title-color "black"
   You have to ensure that the curved edges on the above are, indeed, single edges. You will run into meshing issues if this is not the case.
   If not, you will have to use the "Merge Edges" tool in the Part module and individually select each edge and merge them.
   #+ATTR_HTML: :width 600px
   [[./figs/medg.png]]
   #+end_Details
3. Create a Reference Point Part called =REFPT=.
   This will be necessary for the application of bolt prestress (see [[cref:sec:boltprel]] below).
   #+begin_src python +n :tangle yes
     rpt = mdl.Part(name='REFPT', dimensionality=THREE_D, 
                    type=DEFORMABLE_BODY)
     rpt.ReferencePoint(point=(0.0, 0.0, 0.0))

     rpt.Set(name='Set-1', referencePoints=rpt.referencePoints.values())
   #+end_src
4. Now import the nuts, washers and bolts by importing the file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/c_nutwasherbolt_516.py]].
   You should be able to see the nut, washer and bolt, along with the half beam and reference point created before, as follows after importing:
   #+ATTR_HTML: :width 600px
   [[./figs/nwb.png]]
   The Python script also assigns the material "STEEL" (see above) to the parts.

The file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step0.cae][model\under{}step0.cae]] stores the CAE file at the end of the above steps (building parts, and partitioning).
** Creating appropriate surface sets                                   :GUI:
:PROPERTIES:
:CUSTOM_ID: sec:setcreat
:END:
It is necessary to choose appropriate surface sets for the constraint enforcement and, eventually, the interfacial mesh extraction.
Doing this with surfaces (before meshing) is advantageous since the same scripts can be reused even if the model is remeshed.
1. First select the *interfacial faces* on the half beam model and assign the name =INSURF= to it.
   You can do this through =Tools->Surface->Create= and then selecting the appropriate faces through the GUI.
   Select the faces by holding =Shift= and deselect by holding =Ctrl=.
   Here is a picture of the surface highlighted in the viewport.
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/insurf.png]]
2. Turn to the /outside/ of the beam and select the faces around the bolts individually and name them =BmW1=, =BmW2=, and =BmW3= respectively.
   These will be tied to the washer for the analysis. (=BmWi= denotes the i^{th} Beam-Washer contact).
   Here is a picture of the relevant surfaces highlighted (using different colors for each).
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/bmwsurfs.png]]
3. Create two surfaces on the =BOLT= model as shown in the figure below.
   Name the surface marked white as =BlW= and the surface marked green as =BN=.
   (=BlW= denotes the Bolt-Washer contact surface; =BN= denotes the Bolt-Nut contact surface)
   #+ATTR_HTML: :width 200px
   #+ATTR_LATEX: :width 0.4\textwidth
   [[./figs/boltsurfs.png]]
4. Create two surfaces on the =NUT= model as shown in the figure below.
   Name the white surface as =NW= and the green surface as =NB=.
   (=NW= denotes the Nut-Washer contact surface; =NB= denotes the Nut-Bolt contact surface)
   *Note the direction axes carefully.*
   #+ATTR_HTML: :width 200px
   #+ATTR_LATEX: :width 0.4\textwidth
   [[./figs/nutsurfs.png]]
5. Create two surface on the =WASHER= model and label them as =WSTOP= and =WSBOT= (short for Washer-Surface Top and Bottom).
   Here is a graphical depiction of the model with the surfaces.
   #+ATTR_HTML: :width 200px
   #+ATTR_LATEX: :width 0.4\textwidth
   [[./figs/wshrsurf.png]]

Now all the parts have been created and relevant surfaces have been identified.
*Note*: It is important to have traceable but short names so that a lot of the repetitive tasks can be sped up considerably using scripting.
** Create Assembly                                                     :GUI:
*Note*: While importing the parts, choose Instance Type as "Independent (Mesh on Instance)".
This will be advantageous if we want to modify the meshes just at the interface for mirror symmetry.
We will do independent meshing since it is good practice, although independent meshes are not a requirement for this example (dependent meshes can be used due to symmetry).

1. Import the two beams and re-orient/move them as follows.
   *Note that the bolt-axis has to be pointed in the +z direction.*
   This will be the convention followed throughout this tutorial.
   The green beam in the following is renamed as =TOPBEAM= and the white beam in the following is renamed as =BOTBEAM=.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/asb1.png]]
2. Import one instance each of the =BOLT= and =NUT= and 2 instances of the =WASHER= and assemble them as shown.
   Ensure that the washer is oriented (on each side) with the =WSTOP= oriented in the ~-z~ direction and the =WSBOT= is oriented in the ~+z~ direction.
   Rename the washer instances in the top and bottom as =TOPWASHER-1= and =BOTWASHER-1= respectively.
   Rename the bolt and nut as =NUT-1= and =BOLT-1= respectively.
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/asbwn.png]]
3. Import one instance of the reference point =REFPT=.
   As mentioned before, this will be used to enforce bolt prestress.
   This will be achieved by first placing it at the centroid of the intersection of the =BOLT= and =NUT= (surfaces =BN= and =NB=).
   It is important that the reference point is placed at the centroid.
   This can be done in the GUI by first moving it to an external point and then translating it along the axis.
   The figure below shows an example (a datum point was used for this here).
   Rename this to =BPT-1= (standing for Bolt Point 1).
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/asrpt.png]]
4. Now import another instance of the reference point =REFPT= and translate it to be coincident with =BPT-1=.
   Rename this =NPT-1= (standing for Nut Point 1).
   These two points will have to be on the same geometrical point but equal and opposite forces will be applied for the force application (see [[cref:sec:boltprel]] below for those steps).
   The point =BPT-1= will be coupled to the bolt surface =BN= and =NPT-1= will be tied to the nut surface =NB= through RBE3 elements.
5. Use the "Linear Pattern" dialog and copy the bolt-washer-washer-nut assembly thrice along the beam such that the assembly is complete.
   The figure below shows the final assembly along with a representation of the names of the different parts.
   Recall that  the beam shown in the figure below is =TOPBEAM= and the hidden one is =BOTBEAM=.
   #+ATTR_HTML: :width 600px
   [[./figs/as3bwn.png]]

Now that the assembly is complete, the relevant constraints will have to be enforced, followed by a realization of the bolt preload.
#+latex: \pagebreak
* Constraints
:PROPERTIES:
:CUSTOM_ID: sec:constr
:END:
** Tie-Constraint Enforcement                                   :Script:GUI:
All the following operations can be conducted in the ~Interaction~ module in CAE.
But since selecting each surface can be a time-consuming process, we use the following for-loop in ABAQUS-python (either call it as a script or just copy paste it into the CLI) to make the required tie constraints.
Specifically, it ties the Bolt-Washer, Nut-Washer, and Washer-Beam surfaces.
Note that in the last set of constraints, we recall the fact that the bottom beam is flipped.
So =WASHER-1= is tied to =BmW3= of the bottom beam (and so on for 2,3).
#+begin_src python -n
  mdl = mdb.models['Model-1']
  ras = mdl.rootAssembly

  for i in range(1, 4):
      # Bolt-Washer Constraints
      mdl.Tie(name='BW-%d' %(i),
              main=ras.instances['TOPWASHER-%d' %(i)].surfaces['WSTOP'],
              secondary=ras.instances['BOLT-%d' %(i)].surfaces['BlW'],
              positionToleranceMethod=COMPUTED, adjust=ON,
              tieRotations=ON, thickness=ON)

      # Nut-Washer Constraints
      mdl.Tie(name='NW-%d' %(i),
              main=ras.instances['BOTWASHER-%d' %(i)].surfaces['WSBOT'],
              secondary=ras.instances['NUT-%d' %(i)].surfaces['NW'],
              positionToleranceMethod=COMPUTED, adjust=ON,
              tieRotations=ON, thickness=ON)

      # TopWasher-Beam Constraints
      mdl.Tie(name='BmTW-%d' %(i),
              main=ras.instances['TOPBEAM'].surfaces['BmW%d' %(i)],
              secondary=ras.instances['TOPWASHER-%d' %(i)].surfaces['WSBOT'],
              positionToleranceMethod=COMPUTED, adjust=ON,
              tieRotations=ON, thickness=ON)

      # BotWasher-Beam Constraints
      mdl.Tie(name='BmBW-%d' %(i),
              main=ras.instances['BOTBEAM'].surfaces['BmW%d' %((3-i)%3+1)],
              secondary=ras.instances['BOTWASHER-%d' %(i)].surfaces['WSTOP'],
              positionToleranceMethod=COMPUTED, adjust=ON,
              tieRotations=ON, thickness=ON)
#+end_src
** Bolt Preload Realization                                     :Script:GUI:
:PROPERTIES:
:CUSTOM_ID: sec:boltprel
:END:
You might already have encountered the different parts of the model above that were carefully constructed for the bolt preload application (bolt-shank partitioning, reference points, etc.).
#+begin_Details What's wrong with the inbuilt Bolt Pretension in ABAQUS? :background-color "#cccccc" :title-color "black"
*The ABAQUS Approach*
+ You can find the ABAQUS documentation for the bolt load [[https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/usi/default.htm?startat=pt04ch21s02s01.html][here]].
+ ABAQUS/CAE applies bolt load by specifying a *bolt cross-section*, a *bolt axis*, and the *bolt load*.
+ The documentation for the ABAQUS implementation can be found [[https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/usb/default.htm?startat=pt07ch27s05aus102.html#usb-prc-ppretension][here]].
+ The load is applied in the context of a constraint:
  + It can be a load constraint wherein the displacements/strains at the cross-section are adjusted to match the load.
  + It can be a deformation constraint, wherein the loads are adjusted.
+ In either case, the bolt load *can not be written down as a constant load vector* that can be exported/used elsewhere.
+ It is therefore not possible to use the inbuilt bolt pretension in a substructured analysis, for example.
+ Here are the [[https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/usb/default.htm?startat=pt07ch27s05aus102.html#usb-prc-ppretension][documented limitations]]:
  + An assembly load cannot be specified within a substructure.
  + If a submodeling analysis is performed, any pre-tension section should not cross regions where driven nodes are specified.
  + Nodes of a pre-tension section should not be connected to other parts of the body through multi-point constraints.

*Our Approach*
+ Our method of bolt pretension application addresses all the above issues pertaining to substructuring/submodeling by using *Distributed Coupling* elements (aka RBE3/Spider elements in other FE software).
+ We will first couple the bolt-shank area that is in contact with the nut (the thread area) to a 6DOF point (3 translations + 3 rotations), and do the same for the nut inner surface, with another point, using *Distributed coupling* elements.
+ The bolt and nut will be "fastened" by arresting every DOF in these two nodes except the axial DOF. This will ensure that the only relative displacement between the bolt and nut are axial, which may result from tightening/loosening of the bolt.
+ A *"pulling force" is applied on the bolt-coupling node*, which acts as the tension on the bolt, and a *"pushing force" is applied on the nut-coupling node*, which acts to maintain the system's equilibrium, i.e., fastening.
+ It is understood that there is an interface that the assembly is tightening, which should provide the required reaction forces to balance everything out.
+ Now, the bolt load is merely a constant force vector which can be manipulated as one desires.
#+end_Details

We will now go through the process of specifying this.
1. First couple the bolt-shank surface =BN= with the appropriate reference point (=BPT-n=).
   This can be done in CAE through ~Interaction->Create Constraint->Tie~.
   The following is python code that will do this in a loop.
   #+begin_src python +n
     # Bolt and Nut Point Coupling
     for i in range(1, 4):
         mdl.Coupling(name='BPC-%d' %(i),
                      controlPoint=ras.instances['BPT-%d' %(i)].sets['Set-1'],
                      surface=ras.instances['BOLT-%d' %(i)].surfaces['BN'],
                      influenceRadius=WHOLE_SURFACE, couplingType=STRUCTURAL,
                      weightingMethod=UNIFORM)

         mdl.Coupling(name='NPC-%d' %(i),
                      controlPoint=ras.instances['NPT-%d' %(i)].sets['Set-1'],
                      surface=ras.instances['NUT-%d' %(i)].surfaces['NB'],
                      influenceRadius=WHOLE_SURFACE, couplingType=STRUCTURAL,
                      weightingMethod=UNIFORM)
   #+end_src
2. Now we constrain the X, Y, Rx, Ry, and Rz DOFs (all 5 DOFs other than the Z DOF, which is the bolt-axis) using equation constraints.
   If the bolt axis is not a principal direction in the model, then the constraint equations must be modified appropriately.
   Note that this can also be used in the large deformation context through the use of a local coordinate system (the global CS is used here, so *applicability is restricted to small deformations*).
   This can be done in CAE through ~Interaction->Create Constraint->Coupling~.
   The following code does this through a nested loop such that *=BNEQn-m=  represents the m^{th} DOF constraint at the n^{th} location*.
   #+begin_src python +n
     # Equation Constraints constraining bolt and nut ref-points to each other
     for i in range(1, 4):
         for j in [1, 2, 4, 5, 6]:
             mdl.Equation(name='BNEQ%d-%d' %(i, j),
                          terms=((1.0, 'BPT-%d.Set-1' %(i), j),
                                 (-1.0,'NPT-%d.Set-1' %(i), j)))
   #+end_src
   Here is an image showing the constraints applied graphically.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/conss.png]]
3. We next create a static analysis step (~Step->Create Step->Static, General~) named as =PRESTRESS=.
   This can be done in CAE, but here is the Python code.
   #+begin_src python +n
     mdl.StaticStep(name='PRESTRESS', previous='Initial', nlgeom=ON)
   #+end_src
   *Note*: Nonlinear Geometric effects (nlgeom) is set to ON since this was found to be helpful for convergence of prestress analysis.   
4. We finally apply bolt forces as concentrated forces at the =BPT-n= and =NPT-n= reference points.
   Switch to the =Load= module to do this from CAE.
   The following python code applies a tightening load of 12kN to each bolt.
   #+begin_src python +n
     # Apply forces
     bpmag = 12e3  # 12kN bolt-load
     for i in range(1, 4):
         # Force in +z on bolt-points
         mdl.ConcentratedForce(name='BoltLoad-%d' %(i), createStepName='PRESTRESS',
                               region=ras.instances['BPT-%d' %(i)].sets['Set-1'],
                               cf3=bpmag, distributionType=UNIFORM)
    
         # Force in -z on bolt-points
         mdl.ConcentratedForce(name='NutLoad-%d' %(i), createStepName='PRESTRESS',
                               region=ras.instances['NPT-%d' %(i)].sets['Set-1'],
                               cf3=-bpmag, distributionType=UNIFORM)
   #+end_src
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/loads.png]]
5. *Note* that the bolt load constructed in the above manner is a "linear" load - i.e., the load can be increased/decreased by scaling the resulting force vector.
   It is assumed here that all 3 bolts are loaded equally.
   If this is not the case, the different loads can be exported separately and scaled appropriately (for external analysis).
   It is, however, a physical requirement for equilibrium that =BoltLoad-n= and =NutLoad-n= have to be of equal magnitude and opposite signs.

The file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1.cae][model\under{}step1.cae]] stores the CAE-file generated after the end of the above steps.
We will now proceed with meshing.
#+latex: \pagebreak
* Meshing
:PROPERTIES:
:CUSTOM_ID: sec:meshing
:END:
Since the model is perfectly symmetric, it is sufficient to mesh the model with a global seed, after seeding the interface area locally.
Switch to the =Mesh= module for this section.

If such symmetry is not available, one may choose a more direct approach by using the ~bottom-up~ meshing to copy the mesh from one interface to another directly.
Please [[mailto:nidish.balaji@ila.uni-stuttgart.de][write to me]] if you'd like an example for this.
** Meshing Instructions                                                :GUI:
1. Choose ~Mesh->Assign Mesh Controls~ and select the whole assembly (all the instances).
   We will use a structured hex-dominated element type for the full model (it will give a warning that this is not possible for certain regions. This is okay).
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/globmesh.png]]
2. Now choose ~Mesh->Seed Part Instance~ and select all the instances again.
   Set 0.00254 as the global mesh seed (to ensure 10 elements across thickness) and 0.05 for curvature control.
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/gmeshseed.png]]
3. Apply local seeds at the interface as shown here (on both interfaces).
   Use the ~Mesh->Seed Edges~ tool by choosing the Method as "By Number" and specify the number of elements.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/lmeshseeds.png]]
4. Now mesh the assembly using ~Mesh->Mesh Part Instance~ and selecting all the part instances.
   Here is a view of the interfacial mesh you should get after the above seeding.
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/mesh.png]]
5. Here is an image of the total assembly with the mesh.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/fullmesh.png]]

The file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1a.cae][model\under{}step1a.cae]] stores the CAE-file along with the mesh.
** (Optional, recommended) Verify correctness of model through frictionless prestress :GUI:
:PROPERTIES:
:CUSTOM_ID: sec:abqprs
:END:
We will now conduct a simple frictionless contact analysis to verify the correctness of the model.

*Setup*
1. For the static prestress analysis, first a surface-to-surface contact interaction property has to be created and assigned.
   You can do this from CAE starting from ~Interaction->Create Interaction~ and following the steps in the figure below.
   #+ATTR_HTML: :width 600px
   [[./figs/setcontact.png]]
2. Now create two linear frequency steps, one before and one after the static prestress step, as shown in the figure below.
   Request 30 eigenvalues in each case.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/lfreq.png]]
3. Create 2 jobs. Suppress the interaction property in the first one and have just ~FREQ1~ active (see figure below).
   #+ATTR_HTML: :width 600px
   [[./figs/run1.png]]
   For the second job, suppress ~FREQ1~ and resume the other steps. Resume the surface interaction properties (see figure below).
   #+ATTR_HTML: :width 600px
   [[./figs/run2.png]]
   Optionally, field outputs for ~FREQ2~ (by default it will be set to none if ~FREQ1~ is suppressed).
   You can do this in ~Step->Create Field Outputs~.
   #+ATTR_HTML: :width 300px
   #+ATTR_LATEX: :width 0.5\textwidth
   [[./figs/run2_fo.png]]
*Results*
1. The first analysis should reveal that the system has *7 Rigid Body Modes* (RBMs).
   This is because the two beams are  constrained together in all directions except the axial (where tightening has to happen).
   So the number of RBMs has to be $2\times 6 - 5 = 7$.
   The first 10 modal frequencies have to be (frequencies in cycles/time, or Hz):
   | Index | Frequency |
   |-------+-----------|
   |     1 | 1.0515e-3 |
   |     2 | 1.2851e-3 |
   |     3 | 1.4602e-3 |
   |     4 | 1.6246e-3 |
   |     5 | 1.6592e-3 |
   |     6 | 1.8082e-3 |
   |     7 | 1.9025e-3 |
   |     8 |    70.323 |
   |     9 |    151.26 |
   |    10 |    609.25 |
   In the above, modes 1-7 are RBMs and modes 8 onwards are the elastic modes.
   Looking at the mode-shapes should make it clear that the two beams are free to move axially (the following is mode 1, for eg).
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/res1.png]]
2. The second analysis should converge within a few iterations.
   If not, the "Initial Increment Size" in ~Step->PRESTRESS->Edit->Increment->Initial Increment Size~ has to be reduced.
   If it doesn't converge, try to apply a boundary condition to make the problem well-posed, and try again.
   If it still doesn't converge, check your model again.
   Here is a picture of the contact pressures at the interface at the end of the static prestress step.
   #+ATTR_HTML: :width 400px
   #+ATTR_LATEX: :width 0.55\textwidth
   [[./figs/res2_1.png]]
3. By default, ABAQUS *fuses the nodes* that are in contact at the end of the hard contact step, for the eigenvalue analysis that follows it (Linear Perturbation step).
   Since we are using frictionless tangential here, the tangential DOFs are not fused.
   Here are the first 10 frequencies from the =FREQ2= step (frequencies in cycles/time, or Hz):
   | Index | Frequency |
   |-------+-----------|
   |     1 |      0.00 |
   |     2 |      0.00 |
   |     3 |      0.00 |
   |     4 |      0.00 |
   |     5 |      0.00 |
   |     6 | 2.2068e-3 |
   |     7 |    141.10 |
   |     8 |    152.42 |
   |     9 |    570.33 |
   |    10 |    643.49 |
   It must be observed that the model, under the prestressed state, *has only 6 RBMs*.
   In other words, the bolt-axial direction has now been fixed due to the fact that the contact constraints are active on at least one spot on the interface.
4. If your model passes all the above, then you are ready to proceed.
5. *Note, however, that this does not imply accuracy of the model. One would have to do a mesh convergence analysis in this case.*
   For contact problems, it is well known that the interfacial discretization must be very fine for convergence.
   Much coarser meshes are, however, found to be sufficient for predicting global quantities such as natural frequency and (nonlinear) damping estimates, etc.
   Such a convergence analysis is presented in the appendix of [[https://scholarship.rice.edu/handle/1911/113700][this thesis]]. 

The file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step2.cae][model\under{}step2.cae]] is the cae file containing the model with the above tests included.
#+latex: \pagebreak
* Mesh Process
:PROPERTIES:
:CUSTOM_ID: sec:meshproc
:END:
Now that the model is verified to be correct/consistent, we will proceed with the steps necessary for substructured Matrix Extraction.

Before proceeding it is necessary to first identify nodes on the meshed model that correspond to the input and output locations.
Choose the mid point on the right end as the output node for this tutorial.
Create a node set called =OutNodes= by selecting ~Mesh->Tools->Set->Create->Node~ and choosing the node. Select "unsorted node set" if available.
#+ATTR_HTML: :width 300px
#+ATTR_LATEX: :width 0.5\textwidth
[[./figs/outnode.png]]
It is possible to choose multiple nodes here if you have a MIMO case.

It is also helpful to use global node and element indexing henceforth.
This can be specified in ~Model->Edit Attributes->Model-1~ as follows:
#+ATTR_HTML: :width 300px
#+ATTR_LATEX: :width 0.5\textwidth
[[./figs/modl.png]]
** Reorganize Interfacial Node Sets (readjust if necessary)         :Script:
Although we have taken care to ensure that the mesh of the =TOPBEAM= and =BOTBEAM= are conformal at the interface, minor imperfections in the nodal locations may exist.
Furthermore, the ordering of the nodes on the top interface will be different from that on the bottom interface.
Through some scripting, we can create node sets in such a way that the top and bottom interface nodesets are ordered in a convenient fashion.

You can use the [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1a.cae][model\under{}step1a.cae]] and work along if you are here just for this section.

1. We use the following slightly modified header for this script:
   #+begin_src python -n
     # -*- coding: utf-8 -*-
     # 1. Preamble
     import sys
     import numpy as np

     from part import *
     from material import *
     from section import *
     from assembly import *
     from step import *
     from interaction import *
     from load import *
     from mesh import *
     from optimization import *
     from job import *
     from sketch import *
     from visualization import *
     from connectorBehavior import *

     from abaqus import *
     from abaqusConstants import *
     from caeModules import * 
     import regionToolset
     import job
     import step
     import sets

     mdl = mdb.models['Model-1']
     ras = mdl.rootAssembly

     mdl.setValues(noPartsInputFile=ON)
   #+end_src
2. Now we identify the top and bottom surface nodes, and store the top nodes and elements into separate variables.
   The node and element ordering of the top nodes will be preserved, and the nodes in the bottom will be resorted according to this in #3 below.
   #+begin_src python +n
     # 2. Get top and bottom surfaces and nodes
     topsurf = ras.instances['TOPBEAM'].surfaces['INSURF']
     botsurf = ras.instances['BOTBEAM'].surfaces['INSURF']

     topnodes = topsurf.nodes
     botnodes = botsurf.nodes
     N = len(topnodes)  # Number of nodes

     # Top Nodes and Coordinates
     Topnd_dict = dict(zip([topnodes[i].label
                            for i in range(N)], range(N)))
     # maps original node ID (in FE model) to
     # node ID in interface node set
     TopNdCds = np.array([topnodes[i].coordinates
                          for i in range(N)])

     # Top Elements
     TopEls = np.array([topsurf.elements[i].connectivity
                        for i in range(len(topsurf.elements))])
     ELS = np.zeros((TopEls.shape[0], 5), dtype=int)
     for ne in range(TopEls.shape[0]):
         elefac = topsurf.elements[ne].getElemFaces()

         # Gives you the list of faces on the interface
         # (we only expect a single face here)
         fe = np.argwhere([all([Topnd_dict.has_key(x) for x in 
                                [elefac[k].getNodes()[i].label
                                 for i in range(4)]])
                           for k in range(6)])[0,0]
         ELS[ne, 0] = ne
         # Searches for the face where all the nodes are in the interface
         # and returns those nodes
         ELS[ne, 1:] = [Topnd_dict[x] for x in
                        [elefac[fe].getNodes()[k].label
                         for k in range(4)]]
         ELS[ne, :] += 1

     # Save interfacial nodes and elements to txt files
     np.savetxt('Nodes.dat', TopNdCds) # Save to dat file
     np.savetxt('Elements.dat', ELS, fmt='%d')
   #+end_src
3. Now we extract the bottom nodes and sort them.
   #+begin_src python +n
     # 3. Node Pairing. We assume len(botnodes)=len(topnodes).
     botleft = range(N)
     bts = []
     tmi = 0
     for i in range(N):
         # Calculates deviation of selected node coordinate on bottom to each
         # node coordinate on top and "assigns" the closest one to the index.
         devns = topnodes[i].coordinates - np.array([botnodes[j].coordinates
                                                     for j in botleft])
         bts.append(
             botleft.pop(
                 np.argmin(
                     np.linalg.norm(
                         devns, axis=1)
                 )
             )
         )
   #+end_src
4. We now adjust the nodes on the bottom (this affects the FE mesh directly!)
   #+begin_src python +n
     # 4. Adjust Nodes on Bottom Beam Interface to Match Top Beam Exactly
     for i in range(N):
         ras.editNode(nodes=botnodes[bts[i]:bts[i]+1],
                      coordinates=(topnodes[i].coordinates,))
   #+end_src
5. We now create nodesets for the top (=TOPS_NDS=) and bottom (=BOTS_NDS=).
   #+begin_src python +n
     # 5. Create Node Sets
     botpairednds = botnodes.sequenceFromLabels(tuple([botnodes[i].label
                                                       for i in bts]))
     # Reordering from the sorting above

     ras.SetFromNodeLabels(name="TOPS_NDS", 
                           nodeLabels=((topnodes[0].instanceName, 
                                        tuple([topnodes[i].label
                                               for i in range(N)])),),
                           unsorted=True)
     ras.SetFromNodeLabels(name="BOTS_NDS", 
                           nodeLabels=((botpairednds[0].instanceName, 
                                        [botpairednds[i].label
                                         for i in range(len(botpairednds))]),),
                           unsorted=True)
   #+end_src
   Note that we've used the unsorted keyword to ensure that ABAQUS does not reorder the nodesets (default behavior).
6. We now simplify the model by removing all interaction properties and steps (except initial).
   One side-effect of doing this is that this removes the bolt loads also, since loads can only be saved when there is a corresponding step!
   So we will reintroduce the bolt loads in the substructuring step in #8 below.
   #+begin_src python +n
     # 6. Simplify model (remove interactions, all steps, etc.)
     tmp = mdl.interactions
     while len(tmp) > 0:
         del tmp[tmp.keys()[-1]]

     tmp = mdl.interactionProperties
     while len(tmp) > 0:
         del tmp[tmp.keys()[-1]]

     # Remove all steps except initial
     tmp = mdl.steps
     while len(tmp) > 1:
         del tmp[tmp.keys()[-1]]
   #+end_src
** Setup Fixed interface CMS (HCB-CMS) with linear frequency and substructure steps :Script:
1. We are interested in *Fixed-Interface Component Mode Synthesis* with 20 retained modes.
   So we first do a fixed interface modal analysis and request $20\times3 = 60$ modes (for ensuring accuracy of the first 20 modes).
   We fix all the nodes in the nodesets =TOPS_NDS= and =BOTS_NDS=.
   #+begin_src python +n
     # 7. Create a Frequency Step for fixed interface modal analysis
     mdl.FrequencyStep(name="Fixed-Int-Modal", previous="Initial",
                       normalization=MASS, eigensolver=LANCZOS,
                       numEigen=60)
     mdl.EncastreBC(name="TOPFIX", createStepName="Fixed-Int-Modal",
                    region=ras.sets['TOPS_NDS'])
     mdl.EncastreBC(name="BOTFIX", createStepName="Fixed-Int-Modal",
                    region=ras.sets['BOTS_NDS'])
   #+end_src
2. Next, we create the substructuring step and re-specify the bolt loads (these were removed in #6 above).
   The bolt loads are specified of unit magnitude and can be scaled during analysis.
   *This by default uses the mode shapes from the previous step and calculates static constraint modes automatically.*
   #+begin_src python +n
     # 8. Create a substructuring step, specify the modes and retained DOFs
     mdl.SubstructureGenerateStep(name="HCBCMS", previous="Fixed-Int-Modal",
                                  substructureIdentifier=1, 
                                  retainedEigenmodesMethod=MODE_RANGE,
                                  modeRange=((1, 20, 1),),
                                  recoveryMatrix=REGION,
                                  recoveryRegion=ras.sets['OutNodes'],
                                  computeReducedMassMatrix=True)

     # The name dictates ordering. A comes before B.
     mdl.RetainedNodalDofsBC(name="A", createStepName="HCBCMS", 
                             region=ras.sets['TOPS_NDS'], 
                             u1=ON, u2=ON, u3=ON)
     mdl.RetainedNodalDofsBC(name="B", createStepName="HCBCMS", 
                             region=ras.sets['BOTS_NDS'], 
                             u1=ON, u2=ON, u3=ON)

     # Apply Bolt Loads (1N magnitude)
     for i in range(1, 4):
         mdl.ConcentratedForce(name='BoltLoad-%d' %(i), createStepName="HCBCMS",
                               cf3=1.0,
                               region=ras.instances['BPT-%d' %(i)].sets['Set-1'])
         mdl.ConcentratedForce(name='NutLoad-%d' %(i), createStepName="HCBCMS",
                               cf3=-1.0,
                               region=ras.instances['NPT-%d' %(i)].sets['Set-1'])

     sbs = mdl.steps['HCBCMS']
     sbs.LoadCase(name="LCASE",
                  loads=tuple(('BoltLoad-%d' %(i), 1.0) for i in range(1, 4)) +
                  tuple(('NutLoad-%d' %(i), 1.0) for i in range(1, 4)))
   #+end_src
   Note, in the above that the ordering of the two sets is controlled by the name given to the ~RetainedNodalDofsBC~ function.
   Although the node sets themselves are not sorted, the order in which the nodesets appear is sorted by default.
3. We finally need to request matrix output.
   [[https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/key/default.htm?startat=ch18abk43.html][Here]] is the ABAQUS documentation for the ~*Substructure Matrix Output~ card.
   Thus far (until version 2023) ABAQUS CAE doesn't support requesting matrix output from Substructure steps.
   We have to request this manually in the .inp files.
   Thankfully we can write to the keywords directly from CAE.
   Go to ~Model->Edit Keywords->Model-1~ to do this in the GUI.
   In scripting, this is known as a "synch" operation, which is done as follows:
   #+begin_src python +n
     # 9. Request substructure matrix outputs
     # ABAQUS CAE doesn't support this yet (GUI or scripting),
     # so the keywords need to be manually modified.
     mdl.keywordBlock.synchVersions(storeNodesAndElements=False)

     li = np.argwhere([mdl.keywordBlock.sieBlocks[i][0:20] == "*Retained Nodal Dofs"
                       for i in range(len(mdl.keywordBlock.sieBlocks))])[0][0]
     txi = mdl.keywordBlock.sieBlocks[li]
     mdl.keywordBlock.replace(li, "*Retained Nodal Dofs, sorted=NO"+txi[20:])

     mdl.keywordBlock.insert(len(mdl.keywordBlock.sieBlocks)-2, 
                             "*Substructure Matrix Output, FILE NAME=Modelmats, " +
                             "MASS=YES, STIFFNESS=YES, SLOAD=YES, " +
                             "RECOVERY MATRIX=YES")
   #+end_src
4. We then create a job and write it to an "inp" file that can be run from ABAQUS.
    #+begin_src python +n
      # 10. Create a job and write an inp file
      mdb.Job(name="Job", model='Model-1')
      mdb.jobs['Job'].writeInput()
    #+end_src
5. Here is what the final HCBCMS step looks like in this case.
   The most important part is the ~*Substructure Matrix Output~ card in the bottom,
   which we introduced through the "synch" step in #3 above.
   [[https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/key/default.htm?startat=ch18abk43.html][Here]] is the ABAQUS documentation for the ~*Substructure Matrix Output~ card.
   #+begin_src fortran -n
     ,** ----------------------------------------------------------------
     ,** 
     ,** STEP: HCBCMS
     ,** 
     ,*Step, name=HCBCMS, nlgeom=NO
     ,*Substructure Generate, overwrite, type=Z1, recovery matrix=YES,
           nset=OutNodes, mass matrix=YES
     ,*Select Eigenmodes, generate
     1, 20, 1
     ,*Damping Controls, structural=COMBINED, viscous=COMBINED
     ,*Retained Nodal Dofs, sorted=NO
     BOTS_NDS, 1, 3
     TOPS_NDS, 1, 3
     ,** 
     ,** LOAD CASES
     ,** 
     ,*Substructure Load Case, name=LCASE
     ,** Name: BoltLoad-1   Type: Concentrated force   Scale factor: 1
     ,*Cload
     BPT-1_Set-1, 3, 1.
     ,** Name: BoltLoad-2   Type: Concentrated force   Scale factor: 1
     ,*Cload
     BPT-2_Set-1, 3, 1.
     ,** Name: BoltLoad-3   Type: Concentrated force   Scale factor: 1
     ,*Cload
     BPT-3_Set-1, 3, 1.
     ,** Name: NutLoad-1   Type: Concentrated force   Scale factor: 1
     ,*Cload
     NPT-1_Set-1, 3, -1.
     ,** Name: NutLoad-2   Type: Concentrated force   Scale factor: 1
     ,*Cload
     NPT-2_Set-1, 3, -1.
     ,** Name: NutLoad-3   Type: Concentrated force   Scale factor: 1
     ,*Cload
     NPT-3_Set-1, 3, -1.
     ,*Substructure Matrix Output, FILE NAME=Modelmats, MASS=YES,
           STIFFNESS=YES, SLOAD=YES, RECOVERY MATRIX=YES
     ,*End Step
   #+end_src   
   You can find the inp-file generate from the above in [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/demo/Job.inp][Job.inp]].
** Run Job and Generate the mtx file.                            :Script:GUI:
You can now run the Job named "Job" in the GUI, or directly run the "[[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/demo/Job.inp][Job.inp]]" file from the command line using
#+begin_src bash
  abaqus job=Job inp=Job.inp cpus=2 interactive
#+end_src
Once the job is done, it will output the matrix file "Modelmats.mtx" into the working directory.
This, along with the "Nodes.dat" and "Elements.dat" files that were written out earlier, are all we need for external analyses.
#+latex: \pagebreak
* Matrix Extraction + NL-Analysis
:PROPERTIES:
:CUSTOM_ID: sec:mex
:END:
By default, ABAQUS uses the [[https://math.nist.gov/MatrixMarket/][matrix market format]] for the outputted matrices.
Note the following, in terms of format:
+ Each line that starts with an asterix ("*") is a comment.
+ The linear matrices of the current model are fully symmetric.
+ So only the upper triangular parts of the matrices are exported.
+ The load vector is exported as a vector.
+ Columns of the recovery matrix $R$, defined by
  $$ x_{out} = R x_{cms} $$
  where $x_{cms}$ is the vector of DOFs of the CMS model (substructure) and $x_{out}$ are the output DOFs.
  Each column of $R$ is $N_{out}\times 1$, and $R$ is $N_{out}\times N_{cms}$.
** Postprocessing Exported Matrices                                 :Script:
:PROPERTIES:
:CUSTOM_ID: sec:bscr
:END:
1. The first few lines provide the generalized coordinates of the model. The nodes are listed as positive integers and the "modal" DOFs are listed as negative integers.
   This is followed by a list of DOFs active in each set.
2. The STIFFNESS and MASS matrices are respectively prepended by
   #+begin_src fortran
     ,*     MATRIX,TYPE=STIFFNESS
           <Stiffness matrix entries in upper triangular form>

     ,*     MATRIX,TYPE=MASS
           <Mass matrix entries in upper triangular form>      
   #+end_src
3. The load vector (the bolt prestress load, here) is written as,
   #+begin_src fortran
     ,** SUBSTRUCTURE LOAD CASE VECTOR. SLOAD CASE <name>
     ,***CLOAD 
     ,** 1, 1, <entry>
     ,** 1, 2, <entry>
     ,** 1, 3, <entry>
           .
           .
           .
   #+end_src
4. Finally, the recovery matrix is provided row-by-row as
   #+begin_src fortran
     ,*     SUBSTRUCTURE RECOVERY VECTOR CORRESPONDING TO RETAINED DOFS NUMBER 1
           <entries>
     ,*     SUBSTRUCTURE RECOVERY VECTOR CORRESPONDING TO RETAINED DOFS NUMBER 2
           <entries>
           .
           .
           .
   #+end_src
5. In the actual file, the order is STIFFNESS, LOAD, MASS, then SUBSTRUCTURE.
6. The following Bash script processes the output (a stiffness, a mass, a load case, and recovery entries are expected)
   #+begin_src bash -n
     #!/bin/sh

     if [ $# = 2 ]
     then 
         echo "Correct call!"
         OUT=$2
     elif [ $# = 1 ]
     then
         echo "Acceptable call!"
         a="$1"
         OUT="${a%.*}.mat"
     else
         echo "Wrong call - quitting!"
     fi
     echo "Preprocessing mtx files"
     awkcmd1='BEGIN{mstart=0;}
       ($1~/^\*M/){mstart++; next}
       (mstart==1){if($1!~/^\*/){print}else{exit}}'
     awkcmd2='BEGIN{RS=",";ORS="\n"}{print}'
     gawk "$awkcmd1" $1|gawk "$awkcmd2"|gawk '(NF!=0){print}' > ./.STIFFNESS.mtx

     awkcmd1='BEGIN{mstart=0;}
       ($1~/^\*M/){mstart++; next}
       (mstart==2){if($1!~/^\*/){print}else{exit}}'
     awkcmd2='BEGIN{RS=",";ORS="\n"}{print}'
     gawk "$awkcmd1" $1|gawk "$awkcmd2"|gawk '(NF!=0){print}' > ./.MASS.mtx

     awkcmd1='BEGIN{vstart=0;}
       ($0~/^\*\*\*C/){vstart++; next}
       (vstart>0){print $2,$3,$4}
       (vstart>0 && $1!~/^\*\*/){exit}'
     awkcmd2='BEGIN{FS=","}
       {for(i=1;i<=NF;i++)
         printf("%s ", $i);
         printf("\n")}'
     gawk "$awkcmd1" $1|gawk "$awkcmd2" > ./.FVEC.mtx

     awkcmd1='BEGIN{rstart=0}
      ($0~/^\*\* SUBSTRUCTURE REC/){rstart++;
      if(rstart>1){printf("\n")}
      next}
      (rstart!=0 && $1~/\*\*/){
      for(i=2;i<=NF;i++)printf("%s",$i);}'
     awkcmd2='BEGIN{FS=","}
       {for(i=1;i<=NF;i++)
         printf("%s ",$i);
         printf("\n");}'
     gawk "$awkcmd1" $1|gawk "$awkcmd2" > .RECOV.mtx

     echo "Preprocessing mtx files done"

     python <<EOF
     import numpy as np
     import scipy.io as io

     print("Reading Mass Matrix from mtx file.");
     Mv = np.loadtxt('.MASS.mtx');
     print("Done.");

     print("Reading Stiffness Matrix from mtx file.");
     Kv = np.loadtxt('.STIFFNESS.mtx');
     print("Done.");

     print("Reading Recovery Matrix from mtx file.");
     R = np.loadtxt('.RECOV.mtx');
     print("Done.");

     print("Processing Matrices.")

     Nelm = len(Mv);
     Nelk = len(Kv);
     if (Nelm!=Nelk):
             sys.exit("GIGO - Mass & Stiffness not of same length.");
     Nel = Nelm;

     Nd = ((np.sqrt(1+8*Nel)-1)/2).astype(int); # Solution of Nd(Nd+1)/2-Nel = 0

     M = np.zeros((Nd,Nd));
     K = np.zeros((Nd,Nd));

     (xi,yi) = np.tril_indices(Nd);
     M[xi,yi] = Mv;
     M[yi,xi] = Mv;
     K[xi,yi] = Kv;
     K[yi,xi] = Kv;

     print("Done.")

     print("Reading Forcing Vector from mtx file.");
     Fvdat = np.loadtxt('.FVEC.mtx');
     print("Done.");

     print("Processing Force Vector.");
     Fv = np.zeros(M.shape[0]);
     ids = range(np.where(np.diff(Fvdat[:, 1])==0)[0][0], Fvdat.shape[0])
     n1dofnds = Fvdat[ids, 0].astype(int)
     n3dofnds = Fvdat[list(set(range(Fvdat.shape[0]))-set(ids)), 0].astype(int)
     Fv[((n3dofnds-1)*3+np.kron(np.ones(int(len(n3dofnds)/3)),[0, 1, 2])).astype(int)] = \
     Fvdat[list(set(range(Fvdat.shape[0]))-set(ids)), 2]
     print("Whew.")
     Fv[range(-len(n1dofnds), 0)] = Fvdat[ids, 2]
     print("Done.")

     print("Matrix extraction complete - writing mat file")
     dict = {"M": M, "K": K, "R": R.T, "Fv": Fv.reshape((len(Fv),1))};
     io.savemat(".out.mat",dict);
     print("Processing Over")
     EOF
     mv .out.mat $OUT
     rm .STIFFNESS.mtx .MASS.mtx .RECOV.mtx .FVEC.mtx
   #+end_src
   + This bash script first uses [[https://www.gnu.org/software/gawk/manual/gawk.html][GNU Awk]], a simple but powerful utility that allows line-by-line parsing of files.
   + The script also uses the [[https://www.gnu.org/software/coreutils/cut][cut]] utility from [[https://www.gnu.org/software/coreutils/cut][GNU coreutils]] for manipulations.
   + Finally, the script uses Python (compatible with 2/3), involving numpy and scipy.io, for converting the quantities into a MATLAB mat-file that can be loaded on MATLAB.
   + This script can be called as follows:
     #+begin_src bash
       ./readwritematvec.sh Modelmats.mtx
     #+end_src
   + In windows, this can be done either through [[https://www.cygwin.com/][Cygwin]] or [[https://learn.microsoft.com/en-us/windows/wsl/install][Windows Subsystem for Linux]].
7. It may be possible to do this natively in MATLAB, but since this requires a line-parser, awk is better suited for the job than MATLAB.
   A MATLAB implementation might require loading the whole file into memory for speed.
   Line-parsing on MATLAB was extremely slow for me.
The file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step3.cae][model\under{}step3.cae]] is the final cae file that contains all of the above.
** Nonlinear Analysis on MATLAB/OCTAVE in under 100 lines of code   :Script:
:PROPERTIES:
:CUSTOM_ID: sec:nlan
:END:
We will now do our first nonlinear analysis on MATLAB/OCTAVE with the exported matrices.
We will conduct a *Nonlinear Prestress Analysis* for a frictionless contact with a unilateral spring on the normal direction.

It is assumed that the [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/readwritematvec.sh][readwritematvec.sh]] routine has been called on matrix file named ~Modelmats.mtx~ to produce ~Modelmats.mat~ mat-file.
Further, the nodes and elements on the interface are taken to be available in ~Nodes.dat~ and ~Elements.dat~ files respectively.
The below tutorial is meant to be minimal so it is assumed that all the elements are linear QUAD elements.
1. We start with the preamble for the MATLAB file, then read the mesh information, and then load up the matrices from the ~Modelmats.mat~ file.
   #+begin_src octave -n
     clc
     clear all

     set(0,'defaultAxesTickLabelInterpreter', 'default');
     set(0,'defaultTextInterpreter','latex');
     set(0, 'DefaultLegendInterpreter', 'latex');
     set(0,'defaultAxesFontSize',13);

     %% Read Nodes and Elements
     Nodes = dlmread('./Nodes.dat');
     Elements = dlmread('./Elements.dat');
     N = size(Nodes,1);  % Number of nodes per side
     Ne = size(Elements,1);  % Number of elements

     %% Load Matrices
     fname = './Modelmats.mat';
     load(fname, 'M', 'K', 'R', 'Fv');

     % Number of generalized modal DOFs
     Nint = size(M,1)-(2*N)*3;
   #+end_src
2. It may be tempting to want to use *node-to-node contact elements*.
   But this is *inconsistent here* since the elements have non-uniform area and have non-trivial connectivity.
   In the continuous case, the nodal-force-traction relationship is expressed as
   $$ f_j = \int_\Omega \mathbb{N}_j t(\mathbb{x}) d\Omega, $$
   where $\mathbb{N}_j$ is the $j^{th}$ shape function, $f_j$ is the nodal force of the $j^{th}$ node, and $t(\mathbb{x})$ is the traction-field (of the appropriate traction).\\
   *Contact-constitutive models are understood as local relationships between the relative displacement and contact tractions.*
   Nodal forces are merely integral effects of the local traction distributions.\\
   It is therefore *necessary to employ quadrature integration* for consistency.
3. The implementation greatly simplifies if we were to employ only a single Quadrature Point (QP) per element.
   We construct two matrices, $Q_m$ and $T_m$ such that
   \begin{align*}
   x_{QP} &= Q_{m} x_N \text{, and}\\
   f_N &= T_{m} t_{QP}.
   \end{align*}
   Here, $x_{QP}$ and $x_N$ are the vector of displacements at quadrature points and nodal points respectively; and
   $f_N$ and $t_{QP}$ are the vector of nodal forces and quadrature point tractions respectively.
   #+begin_src octave +n
     %% Single-Point-Quadrature Matrices
     Qm = zeros(Ne, N);  % Each element has one quadrature point
     Tm = zeros(N, Ne);  % Each quadrature pt integrated to 4 nodes
     Ars = zeros(Ne, 1);  % Vector of areas of each element
     for ei=1:Ne
         ndis = Elements(ei, 2:end);  % Nodes of the current element
         Qm(ei, ndis) = ones(1, 4)/4;
                     % value @ QP = avg of nodal values

         Ars(ei) = polyarea(Nodes(ndis,1), Nodes(ndis,2));

         Tm(ndis, ei) = ones(4, 1)*Ars(ei)/4;
                     % (integrated) nodal value = value @ QP times element Area/4
     end
     % Qm is quadrature interpolation matrix
     % Tm is quadrature integration matrix

     Ar_tot = 120e-3*25.4e-3-3*pi*(0.85e-2/2)^2; % True total area
                                                 % Rectangle-3*Circles
     Ar_avg = Ar_tot/Ne;  % Average element area
   #+end_src
   The fact that for a single quadrature point case, the quadrature point is exactly at the centroid of the element.
   For the integral, this assumes that the traction field within each element is uniform, so the integral may be simplified as
   $$ f_j = \int_{\Omega_e} \mathbb{N}_j t(\mathbb{x}) d\Omega \approxeq t_{QP} \underbrace{\int_{\Omega_e} \mathbb{N}_j d\Omega}_{A_e/4,} $$
   with $A_e$ denoting element area, and $\Omega_e$ denoting element domain (surface).
   The interpolation and integration weights are, therefore, easily specified.
   The following is a depiction of the quadrature points against the interfacial elements.
   #+ATTR_HTML: :width 600px
   #+ATTR_LATEX: :width \textwidth
   [[./figs/quadpts.png]]
4. We now construct a matrix $L_{rel}$ such that $L_{rel}x_{cms}$ gives an $N\times 1$ array of interfacial relative displacements in the normal direction.
   This is written based on the fact that the CMS model first lists out all the nodal DOFs of the top interface ($x, y, z$, in that order), and then lists out the DOFs of the bottom interface nodes.
   So the relative normal displacement is defined as $\Delta z:=x_{z,top}-x_{z,bot}$, such that $\Delta z>0$ implies contact and $\Delta z<0$ implies separation.

   The following code derives the matrix $L_{rel}$ to obtain the relative displacement at the quadrature location from the system's global vector of DOFs (CMS DOFs).
   Further, a matrix $G_{rel}$ is also constructed such that $G_{rel} t_{z,rel,QP}$ represents the nodal forces when $t_{z,rel,QP}$ is the normal tractions at the quadrature points.
   Finally, nodal relative displacements are also computed (just for plotting purposes).
   #+begin_src octave +n
     %% Contact Relative Displacements
     Lz = kron(Qm, [0 0 1]); % Get only normal displacement
     Lrel = [Lz -Lz zeros(Ne, Nint)];
     % Lrel defd such that Lrel*x>0 implies contact and Lrel*x<0 implies separation.

     Gz = kron(Tm, [0; 0; 1]);
     Grel = [Gz; -Gz; zeros(Nint, Ne)];

     % Nodal relative disp (only for plotting)
     Lz_n = kron(eye(N), [0 0 1]); % Get only normal displacement
     Lrel_n = [Lz_n -Lz_n zeros(N, Nint)];
   #+end_src
5. Now we construct a null-space projection matrix $L_n$ such that $x_{cms} = L_n x_{nred}$, where $x_{nred}$ is the null space reduced set of DOFs ($N_{cms}-6$).
   Note that the matrix $L_1^T K L_1$ has only 6 RBMs (and not 7) since the interfaces have been stuck together by the $L_1$ matrix.
   #+begin_src octave +n
     %% Remove fixed interface null-space
     L1 = null(Lrel);
     [V,D] = eigs(L1'*K*L1, L1'*M*L1, 20, 'SM'); % Get first 20 modes
     Ln = null(V(:, 1:6)'*L1'*M);  % First six modes are RBMs

     Nn = size(Ln, 2);  % Null-reduced DOFs
   #+end_src
6. Now conduct the nonlinear prestress simulation using a uniform penalty stiffness of $5\times 10^6 Pa m^{-1}$ (units of traction per displacement).
   The normal contact is simulated using a penalty stiffness formulation for simplicity.
   #+begin_src octave +n
     %% Solve the Nonlinear Static Prestress Problem
     bpmag = 12e3;
     knl = 5e6/(Ar_tot/Ne); % knl divided by avg element area
     U0 = (Ln'*K*Ln + (Grel'*Ln)'*(Lrel*Ln)*knl)\(Ln'*Fv*bpmag);

     opt = optimoptions('fsolve', 'specifyObjectiveGradient', true, ...
                        'Display', 'iter');
     [U0, ~, ~, ~, J0] = fsolve(@(U) RESFUN([U; bpmag], Ln'*K*Ln, Ln'*Fv, ...
                                            Lrel*Ln, Ln'*Grel, knl), U0, opt);

     %% Linearized Modal Analysis
     [V0, D0] = eigs(J0, Ln'*M*Ln, 10, 'SM');
     W0 = sqrt(diag(D0));
     disp(table((1:10)', W0/2/pi, 'VariableNames', ...
                {'Index', 'Frequency (Hz)'}))
   #+end_src
   The last few lines conduct a modal analysis from the prestressed state.
   As of the time of writing, convergence was observed in about 21 iterations (using MATLAB R2022a).
   This prints the following table of the elastic modes:
   | Index | Frequency (Hz) |
   |-------+----------------|
   |     1 |         143.74 |
   |     2 |          151.3 |
   |     3 |         575.08 |
   |     4 |         642.81 |
   |     5 |         870.59 |
   |     6 |         945.37 |
   |     7 |         1130.3 |
   |     8 |         1476.4 |
   |     9 |         1701.3 |
   |    10 |         1893.6 |
This completes the analysis, and the next two action points will do some plotting of the results.

   #+begin_details Static Residue Routine RESFUN.m :background-color "#cccccc" :title-color "black"
   The following routine returns the quasi-static residue for a given normal load.
   Only a unilateral spring is considered in the normal direction.
   #+begin_src octave
     function [R, dRdU, dRdf] = RESFUN(Uf, K, Fv, Lc, Gc, knl)
         fnl_pred = knl*Lc*Uf(1:end-1);	% Predicted normal force
         fnl = max(fnl_pred, 0);		% Saturated @ 0: unilateral spring

         jnl = knl*Lc;			% Jacobian
         jnl(fnl==0,:) = 0;			

         % Static Residue
         R = K*Uf(1:end-1)+Gc*fnl - Fv*Uf(end);
         dRdU = K+Gc*Lc*knl;
         dRdf = -Fv;
     end
   #+end_src
   #+end_details
*** Plotting
1. We next construct a ~MATLAB Graph~ object using the element information and plot out the relative normal displacements at the interface as a graph.
   #+begin_src octave
     %% Depict Interfacial Displacement Field
     A = zeros(N);  % Graph adjacency matrix
     for ei=1:Ne
            ndis = Elements(ei, 2:end);  % Nodes of the current element
            A(ndis, ndis([2:end 1])) = A(ndis, ndis([2:end 1])) + eye(4);
            A(ndis([2:end 1]), ndis) = A(ndis([2:end 1]), ndis) + eye(4);
     end
     G = graph(A);

     figure(1)
     pos=get(gcf, 'Position');
     set(gcf, 'Position', [pos(1:2) 900 320], 'Color', 'white')
     clf()
     plot(G, 'XData', Nodes(:,1), 'YData', Nodes(:,2), ...
          'NodeCData', Lrel_n*Ln*U0, ...
          'MarkerSize', 4, 'LineWidth', 3)
     colormap(jet)
     grid on
     axis equal
     axis tight
     set(gca, 'XTick', (-6:3:6)*1e-2)
     xlabel('X Coordinate (m)')
     ylabel('Y Coordinate (m)')
     xx=colorbar('SouthOutside');
     xlabel(xx, 'Nodal Relative Displacement (m)', ...
            'interpreter', 'latex', 'fontsize', 13)
   #+end_src
   The following is the output figure, showing the relative normal displacements at each node, with the nodes connected through the undirected graph constructed using the element information.
   #+ATTR_HTML: :width 600px
   #+ATTR_LATEX: :width \textwidth
   [[./figs/intdisps.png]]
2. We can also plot the interfacial normal tractions by evaluating the contact model at the quadrature points and plotting them.
   Since we have just a single quadrature point per element, each element is filled in with a constant color.
   If multiple quadrature points are available, we can do a least-squares solve to obtain "nodal traction values", which will show the intra-element gradients also.
   #+begin_src octave
     %% Show Pressure field
     pvals = max(knl*Lrel*Ln*U0, 0);  % pressure @ QPs
     figure(3)
     pos=get(gcf, 'Position');
     set(gcf, 'Position', [pos(1:2) 900 320], 'Color', 'white')
     clf()
     for ei=1:Ne
         ndis = Elements(ei, 2:end);  % Nodes of the current element
         fill(Nodes(ndis,1), Nodes(ndis,2), pvals(ei)); hold on
     end
     colormap(jet)
     grid on
     axis equal
     axis tight
     set(gca, 'XTick', (-6:3:6)*1e-2)
     xlabel('X Coordinate (m)')
     ylabel('Y Coordinate (m)')
     xx=colorbar('SouthOutside');
     xlabel(xx, 'Element Normal Pressure (Pa)', ...
            'interpreter', 'latex', 'fontsize', 13)
   #+end_src
   Here is the output of the above plotting.
   The non-trivial normal traction distribution is clearly observed.
   Higher values of $knl$ will obtain a better estimate of the "hard" contact results obtained from ABAQUS earlier.
   An alternative would be to implement a lagrange multiplier method for conducting hard contact simulations directly.
   #+ATTR_HTML: :width 600px
   #+ATTR_LATEX: :width \textwidth
   [[./figs/intpress.png]]
*** Miscellanies
1. Even if all the nodes have equal areas, *node-to-node contact elements are still inconsistent in this context*, since contact interactions can be understood to be a fundamentally local interaction, which need to be integrated to have global influence.
   Quadrature-based integration of local tractions to nodal forces conducts exactly this.
   Please see [[https://www.sciencedirect.com/science/article/abs/pii/S0888327020300017][this paper]] for a quadrature-based implementation for the BRB using a rought contact-based frictional model in the interface.
2. You can quite easily implement a friction model also in ~RESFUN.m~ above.
   This, along with appropriately defined relative displacement matrices will be all you need to get started with your first nonlinear dynamic analysis (that may take more than just 100 lines of code, however ;-) )!
   You can look at [[https://asmedigitalcollection.asme.org/appliedmechanicsreviews/article/72/4/040802/1084997/A-Review-of-Damping-Models-for-Structures-With?casa_token=JWwE4Nf3808AAAAA:266N8zS75p4KrKsaZLrVHrnMfOSyZoq3urnmMf1QbWvJbDrWQYw6FJcpYFmffulGetIYTnMAlA][this paper]] for a list of potential contact models to employ.
3. Do check out [[https://www.sciencedirect.com/science/article/abs/pii/S0888327018305739][QSMA]] (Quasistatic Modal Analysis) and [[https://www.sciencedirect.com/science/article/abs/pii/S0045794919315160][RQNM]] (Rayleigh Quotient-based Nonlinear Modal Analysis).
   These are two powerful quasi-static nonlinear modal analysis approaches that can be implemented using a routine that is not so much more complicated than the above.
   The advantage will be that using such cheap simulations, remarkable insights can be gathered about the (near-resonant) vibration behavior of the structure.
4. It is often beneficial in this context to use *relative coordinates* at the interface (so we can get a 2x reduction in the total number of unknowns in the problem). 
   You can do this in MATLAB on the HCB reduced model, or you can do this directly in the ABAQUS model by introducing ghost nodes representing the relative displacements.
   This is optional, but recommended - see instructions in [[cref:sec:relcsp]].
#+latex: \pagebreak   
* Relative Coordinates Pipeline
:PROPERTIES:
:CUSTOM_ID: sec:relcsp
:END:
In [[cref:sec:meshproc]] and [[cref:sec:mex]], the true nodal DOFS of the interfacial nodes are extracted for the HCBCMS.
Here, we instead extract the relative coordinates directly by introducing a set of *ghost nodes* at the interface whose DOFs are set to be equal to the difference between the DOFs of the top and bottom nodes.
We achieve this by creating Reference Point instances at the appropriate locations and constraining them using the *EQUATION* constraint.

Note that we will first insert the reference points into the model ([[cref:sec:insrpt]]) and the write the resulting model into an inp file.
*I have been unable to figure out a way to do this fully natively with the cae model object, since the node IDs of the reference point instances don't seem to be available unless we are just about to do the analysis.*
If someone can figure this out, please [[mailto:nidbid@gmail.com][write to me]]

We start with the file [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/assembly/model_step1a.cae][model\under{}step1a.cae]] for this.
** Insertion of Reference Point Instances                           :Script:
:PROPERTIES:
:CUSTOM_ID: sec:insrpt
:END:
1. Load the cae file along with the necessary preamble.
   #+begin_src python -n
     import sys
     import numpy as np

     from part import *
     from material import *
     from section import *
     from assembly import *
     from step import *
     from interaction import *
     from load import *
     from mesh import *
     from optimization import *
     from job import *
     from sketch import *
     from visualization import *
     from connectorBehavior import *

     from abaqus import *
     from abaqusConstants import *
     from caeModules import * 
     import regionToolset
     import job
     import step
     import sets

     from inpParser import *

     mdbm = openMdb('./model_step1a.cae')
     mdl = mdbm.models['Model-1']
     ras = mdl.rootAssembly

     mdl.setValues(noPartsInputFile=ON)
   #+end_src
2. Get the nodes of only the top surface
   #+begin_src python +n
     topsurf = ras.instances['TOPBEAM'].surfaces['INSURF']
     topnodes = topsurf.nodes
     N = len(topnodes)  # Number of nodes
     # Top Nodes & Coordinates
     Topnd_dict = dict(zip([topnodes[i].label for i in range(N)], range(N)))
     TopNdCds = np.array([topnodes[i].coordinates for i in range(N)])
   #+end_src
3. Import the reference point (partname: =REFPT=) as instances into the assembly and move them to the nodal locations.
   #+begin_src python +n
     rpt = mdl.parts['REFPT']
     for i in range(N):
         ras.Instance(name='RELPT-%d' %(i+1), part=rpt, dependent=OFF)
         ras.translate(instanceList=('RELPT-%d' %(i+1), ), vector=topnodes[i].coordinates)
   #+end_src
4. Create a set of the reference points, then simplify the model, and save the resulting model to an inp file.
   The name of the resulting inp file will be =MeshedModel.inp=.
   #+begin_src python +n
     ras.Set(name='RELCSET',
             referencePoints=[ras.instances['RELPT-%d' %(i+1)].referencePoints[1]
                              for i in range(N)] )

     tmp = mdl.interactions
     while len(tmp) > 0:
         del tmp[tmp.keys()[-1]]

     tmp = mdl.interactionProperties
     while len(tmp) > 0:
         del tmp[tmp.keys()[-1]]

     # Remove all steps except initial
     tmp = mdl.steps
     while len(tmp) > 1:
         del tmp[tmp.keys()[-1]]

     #### 5. Create a Job and write an inp file
     mdbm.Job(name="MeshedModel", model='Model-1')
     mdbm.jobs['MeshedModel'].writeInput()

     mdbm.close()
   #+end_src
** Process the inp-file model, renumber the bottom nodes, and conduct HCBCMS.
1. We first read in the inp file we saved in the above.
   #+begin_src python -n
     import sys
     import numpy as np

     from part import *
     from material import *
     from section import *
     from assembly import *
     from step import *
     from interaction import *
     from load import *
     from mesh import *
     from optimization import *
     from job import *
     from sketch import *
     from visualization import *
     from connectorBehavior import *

     from abaqus import *
     from abaqusConstants import *
     from caeModules import * 
     import regionToolset
     import job
     import step
     import sets

     from inpParser import *

     mdl = mdb.ModelFromInputFile(name='Model-1',
                                  inputFileName='./MeshedModel.inp')
     ras = mdl.rootAssembly
   #+end_src
2. Following a process similar to that in [[cref:sec:meshproc]], we renumber and align the bottom surface nodes to match the top surface nodes.
   Note that since we have read the model from the inp file, all set names are fully upper case, and the concept of instances does not exist any more.
   #+begin_src python +n
     topsurf = ras.surfaces['TOPBEAM_INSURF']
     botsurf = ras.surfaces['BOTBEAM_INSURF']

     topnodes = topsurf.nodes
     botnodes = botsurf.nodes
     N = len(topnodes)  # Number of nodes
     Topnd_dict = dict(zip([topnodes[i].label for i in range(N)], range(N)))
     TopNdCds = np.array([topnodes[i].coordinates for i in range(N)])

     # Top Elements
     TopEls = np.array([topsurf.elements[i].connectivity
                        for i in range(len(topsurf.elements))])
     ELS = np.zeros((TopEls.shape[0], 5), dtype=int)
     for ne in range(TopEls.shape[0]):
         elefac = topsurf.elements[ne].getElemFaces()

         # Gives you the list of faces on the interface (we only expect a single face)
         fe = np.argwhere([all([Topnd_dict.has_key(x) for x in 
                                [elefac[k].getNodes()[i].label for i in range(4)]])
                           for k in range(6)])[0,0]
         ELS[ne, 0] = ne
         # Searches for & returns the face where all the nodes are in the interface
         ELS[ne, 1:] = [Topnd_dict[x] for x in [elefac[fe].getNodes()[k].label
                                                for k in range(4)]]
         ELS[ne, :] += 1
   #+end_src
   1. Resort the bottom nodes
      #+begin_src python +n
        # Re-sort the bottom nodes    
        botleft = range(N)
        bts = []
        tmi = 0
        for i in range(N):
            # Calculates deviation of selected node coordinate on bottom to each
            # node coordinate on top and "assigns" the closest one to the index.
            bts.append(
                botleft.pop(
                    np.argmin(
                        np.linalg.norm(
                            topnodes[i].coordinates-np.array([botnodes[j].coordinates
                                                              for j in botleft]),
                            axis=1)
                    )
                )
            )

        # Adjust Nodes on Bottom Beam Interface to Match Top Beam Exactly
        for i in range(N):
            ras.editNode(nodes=botnodes[bts[i]:bts[i]+1],
                         coordinates=(topnodes[i].coordinates,))

      #+end_src
3. Create node sets for the top, bottom and relative coordinates.
   #+begin_src python +n
     botpairednds = botnodes.sequenceFromLabels(tuple([botnodes[i].label for i in bts]))
     # Reordering from the sorting above

     ras.SetFromNodeLabels(name="TOPS_NDS", 
                           nodeLabels=((topnodes[0].instanceName, 
                                        tuple([topnodes[i].label for i in range(N)])),),
                           unsorted=True)
     ras.SetFromNodeLabels(name="BOTS_NDS", 
                           nodeLabels=((botpairednds[0].instanceName, 
                                        [botpairednds[i].label for i in range(N)]),),
                           unsorted=True)
     rlcn = ras.sets['RELCSET'].nodes
     ras.SetFromNodeLabels(name="RELCSET",
                           nodeLabels=((rlcn[0].instanceName,
                                        [rlcn[i].label for i in range(N)]),),
                           unsorted=True)
   #+end_src
4. We now set equation constraints to set a meaning for the ghost nodes.
   It is possible to provide sets as inputs to the Equation constraint (each node is taken as-ordered).
   #+begin_src python +n
     for i in range(3):
         mdl.Equation(name='RELCS-%d' %(i+1),
                      terms=((1.0, 'TOPS_NDS', i+1),
                             (-1.0, 'RELCSET', i+1),
                             (-1.0, 'BOTS_NDS', i+1)))
   #+end_src
   The constraint represented by the above is
   $$ u^{(i)}_{RELCSET} = u^{(i)}_{TOP} - u^{(i)}_{BOT} \implies
   u^{(i)}_{TOP} - u^{(i)}_{RELCSET} - u^{(i)}_{BOT} = 0 $$
5. We next setup the "fixed interface" CMS by conducting a Frequency step while constraining all the DOFS of the =RELCSET= nodeset to be zero (interface stuck against each other).
   #+begin_src python +n
     mdl.FrequencyStep(name="Fixed-Int-Modal", previous="Initial",
                       normalization=MASS, eigensolver=LANCZOS,
                       numEigen=60)
     mdl.EncastreBC(name="RELFIX", createStepName="Fixed-Int-Modal",
                    region=ras.sets['RELCSET'])
   #+end_src
6. The substructuring step is finally setup.
   We request 6 more modes in =modeRange= since the "fixedInterface= model will have 6 Rigid Body Modes which don't add anything to model accuracy.
   So if 20 generalized modes are desired, we ask for 26. 
   #+begin_src python +n
     mdl.SubstructureGenerateStep(name="HCBCMS", previous="Fixed-Int-Modal",
                                  substructureIdentifier=1, 
                                  retainedEigenmodesMethod=MODE_RANGE,
                                  modeRange=((1, 26, 1),),
                                  recoveryMatrix=REGION,
                                  recoveryRegion=ras.sets['OUTNODES'],
                                  computeReducedMassMatrix=True)

     mdl.RetainedNodalDofsBC(name="A", createStepName="HCBCMS",
                             region=ras.sets['RELCSET'],
                             u1=ON, u2=ON, u3=ON)

     # Apply Bolt Loads (1N magnitude)
     for i in range(1, 4):
         mdl.ConcentratedForce(name='BoltLoad-%d' %(i), createStepName="HCBCMS",
                               cf3=1.0, region=ras.sets['BPT-%d_SET-1' %(i)])
         mdl.ConcentratedForce(name='NutLoad-%d' %(i), createStepName="HCBCMS",
                               cf3=-1.0, region=ras.sets['NPT-%d_SET-1' %(i)])

     sbs = mdl.steps['HCBCMS']
     sbs.LoadCase(name="LCASE", loads=tuple(('BoltLoad-%d' %(i), 1.0)
                                            for i in range(1, 4)) +
                  tuple(('NutLoad-%d' %(i), 1.0) for i in range(1, 4)))
   #+end_src
7. We complete the task by requesting matrix output and outputting node and element information.
   #+begin_src python +n
     # ABAQUS CAE doesn't support this yet (GUI or scripting),
     # so the keywords need to be manually modified.
     mdl.keywordBlock.synchVersions(storeNodesAndElements=False)
     li = np.argwhere([mdl.keywordBlock.sieBlocks[i][0:20] == "*Retained Nodal Dofs"
                       for i in range(len(mdl.keywordBlock.sieBlocks))])[0][0]
     txi = mdl.keywordBlock.sieBlocks[li]
     mdl.keywordBlock.replace(li, "*Retained Nodal Dofs, sorted=NO"+txi[20:])
     mdl.keywordBlock.insert(len(mdl.keywordBlock.sieBlocks)-2, 
                             "*Substructure Matrix Output, FILE NAME=Modelmats,
                             MASS=YES, STIFFNESS=YES, SLOAD=YES, RECOVERY MATRIX=YES")

     # Create a job and write an inp file
     mdb.Job(name="HCBCMSJob", model='Model-1')
     mdb.jobs['HCBCMSJob'].writeInput()

     # Save interfacial nodes & elements to txt files
     np.savetxt('Nodes.dat', TopNdCds) # Save to dat file
     np.savetxt('Elements.dat', ELS, fmt='%d')
   #+end_src
8. The inp file "HCBCMSJob.inp" can be run just as before, and it will generate an mtx file named "Modelmats.mtx".
9. The script [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/readwritematvec.sh][readwritematvec.sh]] can be used to post process this mtx file just as before.    
** Nonlinear Prestress Analysis with MATLAB/OCTAVE
1. The same MATLAB/OCTAVE routines from [[cref:sec:nlan]] can be used here, with minor tweaks to account for the fact that the model is already in the relative coordinates frame.
2. Everything in the preamble is identical to before:
   #+begin_src octave -n
     clc
     clear all

     set(0,'defaultAxesTickLabelInterpreter', 'default');
     set(0,'defaultTextInterpreter','latex');
     set(0, 'DefaultLegendInterpreter', 'latex');
     set(0,'defaultAxesFontSize',13);

     %% Read Nodes and Elements
     Nodes = dlmread('./Nodes.dat');
     Elements = dlmread('./Elements.dat');
     N = size(Nodes,1);  % Number of nodes per side
     Ne = size(Elements,1);  % Number of elements

     %% Load Matrices
     fname = './Modelmats.mat';
     load(fname, 'M', 'K', 'R', 'Fv');

     % Number of generalized modal DOFs
     Nint = size(M,1)-N*3;

     %% Single-Point-Quadrature Matrices
     Qm = zeros(Ne, N);  % Each element has one quadrature point
     Tm = zeros(N, Ne);  % Each quadrature pt integrated to 4 nodes
     Ars = zeros(Ne, 1);  % Vector of areas of each element
     for ei=1:Ne
         ndis = Elements(ei, 2:end);  % Nodes of the current element
         Qm(ei, ndis) = ones(1, 4)/4;
                     % value @ QP = avg of nodal values

         Ars(ei) = polyarea(Nodes(ndis,1), Nodes(ndis,2));

         Tm(ndis, ei) = ones(4, 1)*Ars(ei)/4;
                     % (integrated) nodal value = value @ QP times element Area/4
     end
     % Qm is quadrature interpolation matrix
     % Tm is quadrature integration matrix

     Ar_tot = 120e-3*25.4e-3-3*pi*(0.85e-2/2)^2; % True total area
                                                 % Rectangle-3*Circles
     Ar_avg = Ar_tot/Ne;  % Average element area
   #+end_src
3. Since the DOFs are already relative displacements, we directly use the Quadrature matrices for the extraction:
   #+begin_src octave +n
     %% Contact Relative Displacements (DOFS already in relative coordinates
     Lz = [kron(Qm, [0 0 1]) zeros(Ne, Nint)]; % Get only normal displacement
     Gz = [kron(Tm, [0; 0; 1]); zeros(Nint, Ne)];

     % Nodal relative disp (only for plotting)
     Lz_n = [kron(eye(N), [0 0 1]) zeros(N, Nint)]; % Get only normal displacement
   #+end_src
4. Just as before, we use the null-space to get a well-posed formulation, and then conduct the nonlinear prestress analysis (~RESFUN.m~ is the same as before).
   #+begin_src octave +n
     %% Remove fixed interface null-space
     L1 = null(Lz);
     [V,D] = eigs(L1'*K*L1, L1'*M*L1, 20, 'SM'); % Get first 20 modes
     Ln = null(V(:, 1:6)'*L1'*M);  % First six modes are RBMs

     Nn = size(Ln, 2);  % Null-reduced DOFs

     %% Solve the Nonlinear Static Prestress Problem
     bpmag = 12e3;
     knl = 5e6/(Ar_tot/Ne); % knl divided by avg element area
     U0 = (Ln'*K*Ln + (Gz'*Ln)'*(Lz*Ln)*knl)\(Ln'*Fv*bpmag);

     opt = optimoptions('fsolve', 'specifyObjectiveGradient', true, ...
                        'Display', 'iter');
     [U0, ~, ~, ~, J0] = fsolve(@(U) RESFUN([U; bpmag], Ln'*K*Ln, ...
                                            Ln'*Fv, Lz*Ln, Ln'*Gz, knl), U0, opt);

     %% Linearized Modal Analysis
     [V0, D0] = eigs(J0, Ln'*M*Ln, 10, 'SM');
     W0 = sqrt(diag(D0));
     disp(table((1:10)', W0/2/pi, 'VariableNames', {'Index', 'Frequency (Hz)'}))
   #+end_src
5. Here is the results of the linearized modal analysis:   
   | Index | Frequency (Hz) |
   |-------+----------------|
   |     1 |         143.74 |
   |     2 |          151.3 |
   |     3 |         575.05 |
   |     4 |         642.77 |
   |     5 |          870.5 |
   |     6 |         945.57 |
   |     7 |         1130.3 |
   |     8 |         1475.6 |
   |     9 |         1700.1 |
   |    10 |         1896.2 |
   Comparing this with the predictions from before indicate a very close agreement.
*** Plotting Results
1. We use the following modified version of the plotting code to visualize the response:
   #+begin_src octave -n
     %% Depict Interfacial Displacement Field
     A = zeros(N);  % Graph adjacency matrix
     for ei=1:Ne
            ndis = Elements(ei, 2:end);  % Nodes of the current element
            A(ndis, ndis([2:end 1])) = A(ndis, ndis([2:end 1])) + eye(4);
            A(ndis([2:end 1]), ndis) = A(ndis([2:end 1]), ndis) + eye(4);
     end
     G = graph(A);

     figure(1)
     pos=get(gcf, 'Position');
     set(gcf, 'Position', [pos(1:2) 900 320], 'Color', 'white')
     clf()
     plot(G, 'XData', Nodes(:,1), 'YData', Nodes(:,2), ...
          'NodeCData', Lz_n*Ln*U0, ...
          'MarkerSize', 4, 'LineWidth', 3)
     colormap(jet)
     grid on
     axis equal
     axis tight
     set(gca, 'XTick', (-6:3:6)*1e-2)
     xlim([-1 1]*6e-2)
     ylim([-1 1]*1.27e-2)
     xlabel('X Coordinate (m)')
     ylabel('Y Coordinate (m)')
     xx=colorbar('SouthOutside');
     xlabel(xx, 'Nodal Relative Displacement (m)', 'interpreter', 'latex', 'fontsize', 13)

     print('./intdisps_rc.png', '-dpng', '-r300')

     %% Show Pressure field
     pvals = max(knl*Lz*Ln*U0, 0);  % pressure @ QPs
     figure(2)
     pos=get(gcf, 'Position');
     set(gcf, 'Position', [pos(1:2) 900 320], 'Color', 'white')
     clf()
     for ei=1:Ne
         ndis = Elements(ei, 2:end);  % Nodes of the current element
         fill(Nodes(ndis,1), Nodes(ndis,2), pvals(ei)); hold on
     end
     colormap(jet)
     grid on
     axis equal
     axis tight
     set(gca, 'XTick', (-6:3:6)*1e-2)
     xlabel('X Coordinate (m)')
     ylabel('Y Coordinate (m)')
     xx=colorbar('SouthOutside');
     xlabel(xx, 'Element Normal Pressure (Pa)', 'interpreter', 'latex', 'fontsize', 13)

     print('./intpress_rc.png', '-dpng', '-r300')
   #+end_src
2. Here are the results
   1. Nodal Displacements:
      #+ATTR_HTML: :width 600px
      #+ATTR_LATEX: :width \textwidth
      [[./figs/intdisps_rc.png]]
   2. Interfacial Pressures:
      #+ATTR_HTML: :width 600px
      #+ATTR_LATEX: :width \textwidth
      [[./figs/intpress_rc.png]]
3. The results can be seen to be almost nearly identical to those shown before.
4. Computationally the advantages are clear.
   The size of the model matrices with relative coordinates is 2078, while the size without is 4136.
   Using the relative DOF-coordinates, therefore, *one can achieve an almost 2x reduction in system size*, which is beneficial in every form of analysis.
#+latex: \pagebreak   
* Outro/Contact
:PROPERTIES:
:CUSTOM_ID: sec:outro
:END:
You can contact me at [[mailto:nidish.balaji@ila.uni-stuttgart.de][nidish.balaji@ila.uni-stuttgart.de]] or [[mailto:nidbid@gmail.com][nidbid@gmail.com]] for any questions/suggestions.
Don't forget to check out the repository in github at [[https://github.com/Nidish96/Abaqus4Joints][https://github.com/Nidish96/Abaqus4Joints]].

If you found this useful, please consider citing [[https://www.sciencedirect.com/science/article/abs/pii/S0888327020300017][this paper]] and/or [[https://scholarship.rice.edu/handle/1911/113700][this thesis]].
** Summary
All the scripts used in the tutorial are provided in 
1. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/a_steelmat.py][a\under{}steelmat.py]]: Loading material
2. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/b_halfbm.py][b\under{}halfbm.py]]: Building the half-beam model
3. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/c_nutwasherbolt_516.py][c\under{}nutwasherbolt\under{}516.py]]: Building the bolt, nut, and washer models.
4. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/d_applyconstraints.py][d\under{}applyconstraints.py]]: Applying the relevant constraints and introducing bolt prestress.
5. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/e_nodeproc.py][e\under{}nodeproc.py]]: The postprocessing script create surface node sets and setting up substructure analysis.
6. Files [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/d1_relcs.py][d1\under{}relcs.py]] and [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/e1_relcsnproc.py][e1\under{}relcsnproc.py]] provide replacements for files 4 & 5 above while using relative coordinates.
7. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/scripts/readwritematvec.sh][readwritematvec.sh]]: Contains the mtx reading script written with =bash= and =python=.
8. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/demo/main.m][main.m]]: Contains the MATLAB/OCTAVE file for doing the nonlinear static prestress analysis (also see [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/demo/RESFUN.m][RESFUN.m]] for the residue routine).
9. [[https://github.com/Nidish96/Abaqus4Joints/blob/main/assets/demo/main_rc.m][main_rc.m]]: Contains the MATLAB/OCTAVE file for the nonlinear static prestress analysis using the relative coordinates representation. 
   
The [[https://github.com/Nidish96/Abaqus4Joints][Github repository]] has the above scripts as well as all the cae files.
** Details on this web-page documentation/offering suggestions
+ This website was generated using org-mode on emacs with the Bigblow html theme from
  [[https://github.com/fniessen/org-html-themes][https://github.com/fniessen/org-html-themes]].
  The collapsible details blocks from [[https://github.com/alhassy/org-special-block-extras][org-special-block-extras]] have also been used extensively.
+ The best way to offer suggestions would be to use the [[https://github.com/Nidish96/Abaqus4Joints/blob/main/docs/index.pdf][pdf version]] of the documentation, annotate it and [[mailto:nidish.balaji@ila.uni-stuttgart.de][mail it to me]].
  Alternately, you can also clone the [[https://github.com/Nidish96/Abaqus4Joints][repository]], make changes and create a pull request.

# Local Variables:
# org-html-htmlize-output-type: inline-css
# End:
